### ISSUE TITLE
改用 PDO

### ISSUE THREAD

**Issue by chivincent** [TTPLP/MyMessageBoard#21]
在 PHP 近幾次改版後， mysql_\* 相關函式已經被廢棄

（從 PHP 5.3 就開始提出警告，直到 PHP 7.0 已經正式被廢棄）

雖然短期之間可以使用 mysqli_\* 相關函式作為替用，但為了安全性與未來發展性，建議改用 PDO 作為資料庫連線的媒介。

另外，盡可能不要把使用者的資料拿進去做 SQL Query，除非你已經確定做過很嚴謹的檢查。

同時也建議改用 Prepared Statement 作為增進 SQL 效能與防範 SQL Injection 的手段。

詳情可於 [PHP官方](http://php.net/manual/en/book.pdo.php) 查詢

**Comment by linroex** [comment]
你竟然出現在這裡XDDDD 我有跟他說哈哈，謝啦XD

**Comment by ericmina83** [comment]
感謝兩位！
