### ISSUE TITLE
Coding Style 

### ISSUE THREAD

**Issue by linroex** [TTPLP/MyMessageBoard#3]
- 使用空白做縮排而非 Tab
- 程式碼分段落
- 純 PHP 的檔案不應該有結尾符號（ex message.php）
- 移除無用的函式、方法

**Comment by linroex** [comment]
$tmp_message_name 未使用？

**Comment by ericmina83** [comment]
以上習慣會記得修改。
1. tab 已改用 4 個空白
3. 以後不會在純 php 的檔案中加結尾。
4. 以後會多加注意，目前已將無用的函式移除。
