### ISSUE TITLE
建議把 csv 拿掉，改用 json 來處理

### ISSUE THREAD

**Issue by linroex** [TTPLP/MyMessageBoard#8]
1. 了解 json 是什麼、為什麼要用 json
2. 了解如何把 php 物件轉換成 json
3. 實作 getjson method

**Comment by ericmina83** [comment]
已改用 json 實作

**Comment by ericmina83** [comment]
getjson 相關的 method 實作於 Message class 內，分別是 analyze 和 storeJSON
